controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_home_hello:
    path: "/hello"
    controller: App\Controller\HomeController::hello
app_home_helloworld:
    path: "/helloworld"
    controller: App\Controller\HomeController::helloworld
app_user_register:
    path: "/register"
    controller: App\Controller\UserController::register
app_user_login:
    path: "/login"
    controller: App\Controller\UserController::login
app_user_home:
    path: /
    controller: App\Controller\HomeController::index
app_article_article_detail:
    path: "/article/{id}"
    controller: App\Controller\ArticleController::articleId
app_home_calculatrice:
    path: "/calculatrice/{n1}/{operator}/{n2}"
    controller: App\Controller\CalculatriceController::calculatrice
app_user_showall_users:
    path: "/users_list"
    controller: App\Controller\AccountController::showAllAccount
app_article_showall_articles:
    path: "/articles_list"
    controller: App\Controller\ArticleController::showAllArticle
app_category_all:
    path: "/categories"
    controller: App\Controller\ApiCategoryController::getAllCategories
app_account_all:
    path: "/accounts"
    controller: App\Controller\ApiAccountController::getAllAccounts
app_article_all:
    path: "/articles"
    controller: App\Controller\ApiArticleController::getAllArticles
app_article_id:
    path: "/articles/{id}"
    controller: App\Controller\ApiArticleController::getArticleById
app_user_register_post:
    path: "/register"
    controller: App\Controller\ApiAccountController::addAccount
    methods: ['POST']
app_api_article_add:
    path: "/articleapi"
    controller: App\Controller\ApiArticleController::addArticle
    methods: ['POST']
app_api_category_add:
    path: "/categoryapi"
    controller: App\Controller\ApiCategoryController::addCategory
    methods: ['POST']
app_account_update:
    path: "/account/{email}"
    controller: App\Controller\ApiAccountController::updateAccount
    methods: ['PUT']
app_account_delete:
    path: "/account/{id}"
    controller: App\Controller\ApiAccountController::deleteAccount
    methods: ['DELETE']
app_password_update:
    path: "/account_pass/{id}"
    controller: App\Controller\ApiAccountController::updatePassword
    methods: ['PUT']
app_category_add:
    path: "/category/add"
    controller: App\Controller\CategoryController::addCategory
app_category:
    path: "/category"
    controller: App\Controller\CategoryController::showAllCategories
app_account_add:
    path: "/account/add"
    controller: App\Controller\AccountController::addAccount
app_article_add:
    path: "/articleadd"
    controller: App\Controller\ArticleController::addArticle