controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_home_hello:
    path: "/hello"
    controller: App\Controller\HomeController::hello
app_home_helloworld:
    path: "/helloworld"
    controller: App\Controller\HomeController::helloworld
app_user_register:
    path: "/register"
    controller: App\Controller\UserController::register
app_user_login:
    path: "/login"
    controller: App\Controller\UserController::login
app_user_home:
    path: /
    controller: App\Controller\HomeController::index
app_article_article_detail:
    path: "/article/{id}"
    controller: App\Controller\ArticleController::articleId
app_home_calculatrice:
    path: "/calculatrice/{n1}/{operator}/{n2}"
    controller: App\Controller\CalculatriceController::calculatrice
app_user_showall_users:
    path: "/users_list"
    controller: App\Controller\AccountController::showAllAccount
app_article_showall_articles:
    path: "/articles_list"
    controller: App\Controller\ArticleController::showAllArticle